// Design-system public surface — barrel for the claude.ai/design sync bundle.
// Re-exports every component (incl. compound sub-parts) so window.ClaudeDS.*
// has them all; the DS card list is curated separately via componentSrcMap.
export * from './alert-dialog'
export * from './alert'
export * from './avatar'
export * from './badge'
export * from './button'
export * from './card'
export * from './collapsible'
export * from './confirm-dialog'
export * from './dialog'
export * from './dropdown-menu'
export * from './input'
export * from './label'
export * from './popover'
export * from './scroll-area'
export * from './select'
export * from './separator'
export * from './sidebar'
export * from './skeleton'
export * from './switch'
export * from './textarea'
export * from './toast'
export * from './toggle-group'
export * from './tooltip'
