// Reading sync collections: books / progress / annotations / bookmarks / readingEvents.
// The first four are generated by lwwCollection (progress has no tombstone, the others do); readingEvents is
// hand-written append-only (apply = INSERT OR IGNORE, clear by natural key + dirty=1; rows are immutable).
// The sync engine imports these explicitly and runs them in a fixed order after words→notes→settings→reviewLogs.
//
// Note: this file only handles rows in/out of the change stream. Removing local books/<hash>/ after a pulled
// delete tombstone is file-side orchestration in ./library's purgeRemovedBookFiles (no fs bridge here).
import { and, eq } from 'drizzle-orm'
import type { BatchItem } from 'drizzle-orm/batch'
import type { Db } from '@/db/client'
import {
  userBook,
  userBookAnnotation,
  userBookBookmark,
  userBookProgress,
  userReadingEvent,
} from '@/db/schema'
import { lwwCollection, type LwwCollection } from '@/sync/lww'
import type {
  AnnotationRow,
  BookRow,
  BookmarkRow,
  ProgressRow,
  ReadingEventRow,
} from '@/sync/protocol'

/** books: LWW, natural key bookHash, with tombstones (tombstone = book deleted, propagated). */
export const books: LwwCollection<BookRow> = lwwCollection<BookRow>({
  table: userBook,
  key: [{ col: userBook.bookHash, prop: 'bookHash', wire: true }],
  payload: [
    { col: userBook.title, prop: 'title', default: '' },
    { col: userBook.author, prop: 'author', default: '' },
    { col: userBook.format, prop: 'format', default: 'epub' },
    { col: userBook.importedAt, prop: 'importedAt', default: 0 },
  ],
  hasTombstone: true,
})

/** progress: LWW, natural key bookHash, no tombstone (progress can't be deleted, like settings). */
export const progress: LwwCollection<ProgressRow> = lwwCollection<ProgressRow>({
  table: userBookProgress,
  key: [{ col: userBookProgress.bookHash, prop: 'bookHash', wire: true }],
  payload: [
    { col: userBookProgress.location, prop: 'location', default: '' },
    { col: userBookProgress.fraction, prop: 'fraction', default: 0 },
    { col: userBookProgress.lastReadAt, prop: 'lastReadAt', default: 0 },
  ],
  hasTombstone: false,
})

/** annotations: LWW, natural key annotationId (client UUID), with tombstones. */
export const annotations: LwwCollection<AnnotationRow> = lwwCollection<AnnotationRow>({
  table: userBookAnnotation,
  key: [{ col: userBookAnnotation.annotationId, prop: 'annotationId', wire: true }],
  payload: [
    { col: userBookAnnotation.bookHash, prop: 'bookHash', default: '' },
    { col: userBookAnnotation.cfi, prop: 'cfi', default: '' },
    { col: userBookAnnotation.text, prop: 'text', default: '' },
    { col: userBookAnnotation.color, prop: 'color', default: 'yellow' },
    { col: userBookAnnotation.style, prop: 'style', default: 'fill' },
    { col: userBookAnnotation.note, prop: 'note', default: '' },
    { col: userBookAnnotation.createdAt, prop: 'createdAt', default: 0 },
  ],
  hasTombstone: true,
})

/** bookmarks: LWW, natural key bookmarkId (client UUID), with tombstones. */
export const bookmarks: LwwCollection<BookmarkRow> = lwwCollection<BookmarkRow>({
  table: userBookBookmark,
  key: [{ col: userBookBookmark.bookmarkId, prop: 'bookmarkId', wire: true }],
  payload: [
    { col: userBookBookmark.bookHash, prop: 'bookHash', default: '' },
    { col: userBookBookmark.cfi, prop: 'cfi', default: '' },
    { col: userBookBookmark.title, prop: 'title', default: '' },
    { col: userBookBookmark.createdAt, prop: 'createdAt', default: 0 },
  ],
  hasTombstone: true,
})

// ────────────────── readingEvents: append-only (hand-written, mirrors reviewLogs) ──────────────────

/** Natural key predicate (bookHash, startTime). */
function readingEventKey(row: ReadingEventRow) {
  return and(
    eq(userReadingEvent.bookHash, row.bookHash),
    eq(userReadingEvent.startTime, row.startTime),
  )
}

/** readingEvents: idempotent apply (INSERT OR IGNORE), clear by natural key + dirty=1 (no editTime check). */
export const readingEvents = {
  async collectDirty(db: Db): Promise<ReadingEventRow[]> {
    const rows = await db.select().from(userReadingEvent).where(eq(userReadingEvent.dirty, 1)).all()
    return rows.map(
      (r): ReadingEventRow => ({
        syncVer: 0,
        bookHash: r.bookHash,
        startTime: r.startTime,
        durationMs: r.durationMs,
        fraction: r.fraction,
      }),
    )
  },

  /** Idempotent insert: unique-key conflicts are ignored (re-push / re-pull is harmless); incoming syncVer isn't stored. */
  applyRemoteStmt(db: Db, row: ReadingEventRow): BatchItem<'sqlite'> {
    return db
      .insert(userReadingEvent)
      .values({
        bookHash: row.bookHash,
        startTime: row.startTime,
        durationMs: row.durationMs,
        fraction: row.fraction,
        dirty: 0,
      })
      .onConflictDoNothing()
  },

  /** Clear dirty after a push is accepted: rows are immutable, so (natural key, dirty=1) is enough. */
  clearAcceptedStmts(db: Db, rows: readonly ReadingEventRow[]): BatchItem<'sqlite'>[] {
    return rows.map((row) =>
      db
        .update(userReadingEvent)
        .set({ dirty: 0 })
        .where(and(readingEventKey(row), eq(userReadingEvent.dirty, 1))),
    )
  },
}
