// Reading domain facade — the only entry point for pages/components. It:
// 1. wraps the `vendor/foliate-js` reading engine (see vendor/foliate-js/VENDOR.md) without exposing vendor internals;
// 2. binds the db singleton and the calibrated clock for editTime, composing the pure books/annotations/bookmarks/progress
//    primitives. All writes go through the change stream (rows marked dirty, pushed later).
import { db } from '@/db/client'
import { calibratedNowSync } from '@/sync/clock'
import * as annotations from './annotations'
import * as bookmarks from './bookmarks'
import * as books from './books'
import * as progress from './progress'
import * as tracking from './tracking'
import type { AnnotationRecord, BookRecord, BookmarkRecord, ProgressRecord } from './types'

export { createFoliateEngine } from './engine/foliateEngine'
export type {
  FoliateEngine,
  FoliateLocation,
  FoliateLoadDetail,
  OverlayStyle,
  EngineAnnotation,
  EngineSelection,
  EngineAnnotationHit,
  HandlePoint,
  RangeHandles,
  TocNode,
  TtsSentence,
  AppearanceParams,
  PaginationMap,
} from './engine/foliateEngine'
// CFI → chapter mapping and comparison (group by chapter, sort by position) — wraps vendor epubcfi.
export { compareCfi, findTocItemByCfi, isCfiInSection } from './engine/cfi'
export type { CfiRange } from './engine/cfi'
// Selection → lookup term: cleaning happens engine-side and comes back with the selection;
// pages only decide whether it's lookup-able (empty → hide, too long → fall back to Translate) and the copy.
// `cleanLookupTerm` is also used when tapping an existing highlight (no live selection; cleans the highlight text).
export { cleanLookupTerm, judgeLookupTerm, LOOKUP_MAX_WORDS } from './engine/lookupTerm'
export type { LookupTermVerdict } from './engine/lookupTerm'
export type {
  BookRecord,
  ShelfBook,
  AnnotationRecord,
  BookmarkRecord,
  ProgressRecord,
  ReadingEventRecord,
  HighlightColor,
  HighlightStyle,
} from './types'
export type { AnnotationPatch } from './annotations'
export type { ReadingTracker } from './tracking'

// ── Library (user_book) ──
// Add/delete go through library orchestration (book file and row must change together); no raw primitives exposed.

export { importBook, openBookFile, deleteBook, listShelf, purgeRemovedBookFiles } from './library'
export type { ImportResult } from './library'
/** Get one book (including tombstoned rows): open by hash; import uses isDeleted to tell "already in library" from "revivable". */
export const getBook = (bookHash: string): Promise<BookRecord | null> => books.getBook(db, bookHash)

// ── Highlights (user_book_annotation) ──
// ids are generated by the caller (crypto.randomUUID); color/style/note changes use update, delete writes a tombstone.

export const listAnnotations = (bookHash: string): Promise<AnnotationRecord[]> =>
  annotations.listAnnotations(db, bookHash)
/**
 * Build a new annotation (stamps id and createdAt, **does not persist**): the page shows it first, then saves
 * asynchronously; id and the calibrated clock are data-side concerns, so the facade stamps them here.
 */
export const newAnnotation = (a: Omit<AnnotationRecord, 'id' | 'createdAt'>): AnnotationRecord => ({
  ...a,
  id: crypto.randomUUID(),
  createdAt: calibratedNowSync(),
})
export const addAnnotation = (a: AnnotationRecord): Promise<void> =>
  annotations.addAnnotation(db, a, calibratedNowSync())
export const updateAnnotation = (id: string, patch: annotations.AnnotationPatch): Promise<void> =>
  annotations.updateAnnotation(db, id, patch, calibratedNowSync())
export const removeAnnotation = (id: string): Promise<void> =>
  annotations.removeAnnotation(db, id, calibratedNowSync())

// ── Bookmarks (user_book_bookmark) ──

export const listBookmarks = (bookHash: string): Promise<BookmarkRecord[]> =>
  bookmarks.listBookmarks(db, bookHash)
/** Build a new bookmark (like newAnnotation: stamps id + createdAt, does not persist). */
export const newBookmark = (b: Omit<BookmarkRecord, 'id' | 'createdAt'>): BookmarkRecord => ({
  ...b,
  id: crypto.randomUUID(),
  createdAt: calibratedNowSync(),
})
export const addBookmark = (b: BookmarkRecord): Promise<void> =>
  bookmarks.addBookmark(db, b, calibratedNowSync())
export const renameBookmark = (id: string, title: string): Promise<void> =>
  bookmarks.renameBookmark(db, id, title, calibratedNowSync())
export const removeBookmark = (id: string): Promise<void> =>
  bookmarks.removeBookmark(db, id, calibratedNowSync())

// ── Reading progress (user_book_progress) ──

/** Get where the user left off (null if no progress row). */
export const getProgress = (bookHash: string): Promise<ProgressRecord | null> =>
  progress.getProgress(db, bookHash)
/** Save progress (one row per book, upsert). Caller debounces and flushes before closing. */
export const saveProgress = (bookHash: string, location: string, fraction: number): Promise<void> =>
  progress.saveProgress(db, { bookHash, location, fraction }, calibratedNowSync())

// ── Reading events (user_reading_event) ──

/**
 * Create a reading-time tracker for a book (no UI, capture only): the page feeds position changes and stops;
 * it writes append-only session events. Idle cut-off and s↔ms conversion live here. Always call `stop()` on close.
 */
export const createReadingTracker = (bookHash: string): tracking.ReadingTracker =>
  tracking.createReadingTracker(db, bookHash, calibratedNowSync)
